import React from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Progress } from '@/components/ui/progress'
import { GlobalStats } from '@/components/GlobalStats'
import { BookOpen, Brain, Heart, TrendUp, Target, Clock, GraduationCap, ArrowSquareOut } from '@phosphor-icons/react'

interface DashboardProps {
  userProfile: any
  onNavigate: (view: string) => void
}

export function Dashboard({ userProfile, onNavigate }: DashboardProps) {
  const todaySchedule = [
    { subject: 'Mathematics', time: '9:00 AM', duration: '45 min', confidence: 65 },
    { subject: 'Physics', time: '2:00 PM', duration: '60 min', confidence: 45 },
    { subject: 'Chemistry', time: '4:30 PM', duration: '30 min', confidence: 75 }
  ]

  const weeklyProgress = {
    studyHours: 18,
    goal: 25,
    streakDays: 5,
    wellnessScore: 8.2
  }

  return (
    <div className="space-y-6 p-6">
      <div className="flex flex-col gap-2">
        <h1 className="text-3xl font-bold text-foreground">
          Welcome back, {userProfile?.name || 'Student'}! 👋
        </h1>
        <p className="text-muted-foreground">
          Ready to achieve your learning goals today?
        </p>
      </div>

      {/* Global Student Stats */}
      <GlobalStats />

      {/* Quick Stats */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card className="bg-gradient-to-br from-primary/5 to-primary/10 border-primary/20">
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-primary/10 rounded-lg">
                <Clock className="h-5 w-5 text-primary" />
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Today's Focus</p>
                <p className="text-xl font-semibold">2h 15m</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-gradient-to-br from-secondary/5 to-secondary/10 border-secondary/20">
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-secondary/10 rounded-lg">
                <Heart className="h-5 w-5 text-secondary" />
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Wellness</p>
                <p className="text-xl font-semibold">{weeklyProgress.wellnessScore}/10</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-gradient-to-br from-accent/5 to-accent/10 border-accent/20">
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-accent/10 rounded-lg">
                <Target className="h-5 w-5 text-accent" />
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Study Streak</p>
                <p className="text-xl font-semibold">{weeklyProgress.streakDays} days</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-gradient-to-br from-purple-500/5 to-purple-500/10 border-purple-500/20">
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-purple-500/10 rounded-lg">
                <TrendUp className="h-5 w-5 text-purple-500" />
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Weekly Goal</p>
                <p className="text-xl font-semibold">{Math.round((weeklyProgress.studyHours / weeklyProgress.goal) * 100)}%</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Today's Schedule */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <BookOpen className="h-5 w-5 text-primary" />
                Today's Study Plan
              </CardTitle>
              <CardDescription>
                Your personalized schedule generated by Grade UP AI
              </CardDescription>
            </div>
            <Button onClick={() => onNavigate('planner')} variant="outline" size="sm">
              View Full Plan
            </Button>
          </div>
        </CardHeader>
        <CardContent className="space-y-3">
          {todaySchedule.map((session, index) => (
            <div key={index} className="flex items-center justify-between p-4 bg-muted/50 rounded-lg">
              <div className="flex items-center gap-4">
                <div className="text-center">
                  <p className="text-sm font-medium">{session.time}</p>
                  <p className="text-xs text-muted-foreground">{session.duration}</p>
                </div>
                <div>
                  <p className="font-medium">{session.subject}</p>
                  <div className="flex items-center gap-2 mt-1">
                    <Progress value={session.confidence} className="w-20 h-2" />
                    <span className="text-xs text-muted-foreground">{session.confidence}% confidence</span>
                  </div>
                </div>
              </div>
              <Badge variant={session.confidence < 50 ? 'destructive' : session.confidence < 70 ? 'secondary' : 'default'}>
                {session.confidence < 50 ? 'Focus Needed' : session.confidence < 70 ? 'Review' : 'Confident'}
              </Badge>
            </div>
          ))}
        </CardContent>
      </Card>

      {/* Leaving Certificate Preparation */}
      <Card className="bg-gradient-to-br from-purple-500/5 to-indigo-500/10 border-purple-500/20">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <GraduationCap className="h-5 w-5 text-purple-600" />
            Leaving Certificate Preparation
          </CardTitle>
          <CardDescription>
            Access comprehensive resources and practice materials for your Leaving Cert exams
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex items-center justify-between p-4 bg-white/50 rounded-lg border border-purple-200/50">
            <div>
              <h4 className="font-semibold text-purple-800 mb-1">GradeUp Coach</h4>
              <p className="text-sm text-purple-700">
                Chat with your AI coach for personalized study guidance and support
              </p>
            </div>
            <Button
              onClick={() => window.open('https://nice-coast-0da719e03.2.azurestaticapps.net', '_blank')}
              className="bg-purple-600 hover:bg-purple-700 text-white flex items-center gap-2"
            >
              <ArrowSquareOut className="h-4 w-4" />
              Chat Now
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Quick Actions */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card className="cursor-pointer hover:shadow-md transition-shadow" onClick={() => onNavigate('quiz')}>
          <CardContent className="p-6 text-center">
            <Brain className="h-8 w-8 text-primary mx-auto mb-3" />
            <h3 className="font-semibold mb-2">Quick Quiz</h3>
            <p className="text-sm text-muted-foreground">Test your knowledge with adaptive questions</p>
          </CardContent>
        </Card>

        <Card className="cursor-pointer hover:shadow-md transition-shadow" onClick={() => onNavigate('wellness')}>
          <CardContent className="p-6 text-center">
            <Heart className="h-8 w-8 text-secondary mx-auto mb-3" />
            <h3 className="font-semibold mb-2">Wellness Check</h3>
            <p className="text-sm text-muted-foreground">Take a moment for mental health</p>
          </CardContent>
        </Card>

        <Card className="cursor-pointer hover:shadow-md transition-shadow" onClick={() => onNavigate('progress')}>
          <CardContent className="p-6 text-center">
            <TrendUp className="h-8 w-8 text-accent mx-auto mb-3" />
            <h3 className="font-semibold mb-2">View Progress</h3>
            <p className="text-sm text-muted-foreground">See your learning analytics</p>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}